### ISSUE TITLE
Issue with second colon on image line

### ISSUE THREAD

**Issue by sitestudio** [FranckPachot/ybdemo#3]
Not sure if this is just something odd in my environment, found that I had to remove from the second colon onwards for the gen-yb-docker-compose.sh file to generate a docker-compose.yaml that works.

Otherwise it would complain about "mapping values are not allowed here".

As a result my output docker-compose.yaml file now has:

yb-demo-connect:
   image: yugabytedb/yugabyte       <== no second colon or tag here
   volumes:

**Comment by FranckPachot** [comment]
Got it. I added recently fetching the latest version tag, but if you don't have curl and jq it will not work.
I've added a detault to `latest` in https://github.com/FranckPachot/ybdemo/commit/5cbfa747c54115cd67ba472ce5253c0d41114fb4 - thanks

**Comment by sitestudio** [comment]
It must have been jq, already had curl - works now and on other machines since installing jq.

Also of note, I had to reboot after installing maven at least, possibly jdk too, on Ubuntu 22.04 for the root directory build to work (I think).

Cheers Andrew
